FROM  wso2/wso2am:3.1.0
RUN rm -rf /home/wso2carbon/wso2am-3.1.0/repository/logs
RUN mkdir -p /home/wso2carbon/wso2am-3.1.0/repository/logs
COPY repository/logs /home/wso2carbon/wso2am-3.1.0/repository/logs