version: "3.6"
services:
  appnode-nginx:
    build: ./nginx
    container_name: prod-appnode-nginx
    volumes:
            - ./nginx/logs:/var/log/nginx:rw
            - ./nginx/config:/etc/nginx:rw
            - ./nginx/src:/usr/share/nginx/html:rw
    ports:
            - "80:80"
    restart: "always"
  appnode-wso2am:
    build: ./wso2am
   #image: wso2/wso2am:3.1.0
    container_name: prod-appnode-wso2am
    volumes:
            - ./wso2am/repository/logs:/home/wso2carbon/wso2am-3.1.0/repository/logs:rw
    ports:
        - "8280:8280"
        - "8243:8243"
        - "9443:9443"
    restart: "always"